### ISSUE TITLE
Video includes ~5 minutes of dead time when Avi takes a short break

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/rails-video-review-intro-to-rails#1]
~56:20 --> ~1:01:10

I know these videos aren't meant to be reference-quality recordings, but it'd probably be good to excise that bit.

**Comment by gj** [comment]
Also includes some misfired attempts to use the in-browser Rails console that might be good to clean up.

**Comment by cjbrock** [comment]
Moving to known issue 

// Corinna
