### ISSUE TITLE
I think this video should be at a different point of the curriculum

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/rails-video-review-intro-to-rails#2]
Currently, it's the 6th lesson in Rails, but it deals heavily with Rails generators, which aren't introduced until the 25th lesson.

I think it'd make more sense as a review slotted between **Rails Generators** and **CRU Rails Lab**.

**Comment by AnnJohn** [comment]
we had to remove the videos as separate lessons and added them as video review resources in existing lessons. I moved this to the lesson on generators. thanks!
