### ISSUE TITLE
Suggested Summary

### ISSUE THREAD

**Issue by lennhy** [learn-co-curriculum/rails-video-review-intro-to-rails#3]
This video covers the flow of logic and the process it takes to get from the view to the browser. 
First we need a model then the controller- its action, the routes that match the controller action and the view that it is rendered to. This is then sent to the server which returns the url in the browser. 
Rails has the following components:
ActiveRecordModels - comprises methods for helping build your rails application
ActionController - for controlling the flow of data between the model and the view
Actionview - rendering the view without having to write explicit html.

**Comment by AnnJohn** [comment]
thanks- we added this to the lesson!
