### ISSUE TITLE
Add link to fuller breakdown of Rails directory structure

### ISSUE THREAD

**Issue by marielfrank** [learn-co-curriculum/rails-video-review-intro-to-rails#6]
It seems that the students that Avi was teaching in the video already knew the purpose of `app > assets` and `app > mailer`, etc., but this has yet to be covered within the online curriculum. Add a link to [https://www.sitepoint.com/a-quick-study-of-the-rails-directory-structure/](https://www.sitepoint.com/a-quick-study-of-the-rails-directory-structure/) to give students a clearer understanding of these parts of the Rails file structure. Thanks!

**Comment by curiositypaths** [comment]
Hi there,

Thank you for taking the time to contribute to our curriculum. We will include a link to our [Rails Application Basics](https://github.com/learn-co-curriculum/rails-application-basics-readme) lesson which includes a section describing the Rails directory structure.

Thanks! 💙
